'use strict';
const main=document.querySelector('main');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).replace(/[\u064B-\u065F\u0670ـ]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').trim().toLowerCase();
let progress={};try{const saved=JSON.parse(localStorage.getItem('lughti-curriculum-v2')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))progress=saved}catch{}
let filter='الكل',search='',current=null,quizAnswers={},graded=false,storageOK=true,lastFocus=null,pendingPractice=false;
const categories=['الكل',...new Set(LESSONS.map(x=>x.category))];
const glyphs=['!','نِعْمَ','كان','إنّ','فاعل','مِـ','أ ا','ابن','ئ','ء'];
function best(id){return Number.isInteger(progress[id]?.best)&&progress[id].best>=0&&progress[id].best<=4?progress[id].best:0}
function persist(){try{localStorage.setItem('lughti-curriculum-v2',JSON.stringify(progress))}catch{storageOK=false}}
function card(l){const i=LESSONS.indexOf(l);return `<a class="lesson-card" href="#lesson/${l.id}"><div class="card-top"><span class="glyph" aria-hidden="true">${glyphs[i]}</span><span class="number">${String(i+1).padStart(2,'0')}</span></div><span class="tag">${l.category}</span><h3>${l.title}</h3><p>${l.goal}</p><div class="card-bottom"><span>${progress[l.id]?.done?'تم التدريب · '+best(l.id)+' / ٤':'شرح • أمثلة • تدريب'}</span><span class="arrow" aria-hidden="true">←</span></div></a>`}
function grid(){let list=LESSONS.filter(l=>(filter==='الكل'||l.category===filter)&&norm(l.title+' '+l.goal+' '+l.rules.join(' ')).includes(norm(search)));document.querySelector('#cards').innerHTML=list.length?list.map(card).join(''):'<p class="empty">لم نجد درسًا بهذه العبارة. جرّب كلمة أخرى أو اختر «الكل».</p>';document.querySelector('#count').textContent=list.length+' دروس';}
function home(){main.innerHTML=`<section class="hero"><div><span class="eyebrow">الصف السادس الابتدائي / الفصل الدراسي الأول</span><h1>لغتي أجمل،<br><em>حين أفهمها.</em></h1><p>رحلتك إلى إتقان القواعد تبدأ من هنا. اختر درسك، تأمل الأمثلة، ثم اختبر فهمك خطوة بخطوة.</p><a class="primary" href="#lessons">اكتشف الدروس ←</a><div class="stats"><div><b>١٠</b><small>دروس للمراجعة</small></div><div><b>٤٠</b><small>سؤالًا تدريبيًا</small></div><div><b>٤</b><small>مجالات لغوية</small></div></div></div><div class="hero-art" aria-hidden="true"><span class="float-label one">أفهم القاعدة</span><div class="orbit"><span class="letter">ض</span></div><span class="float-label two">أتعلم وأتقدم</span></div></section><section id="lessons"><div class="section-head"><div><span class="tag">خطوة جديدة نحو الإتقان</span><h2>ماذا سنتعلم اليوم؟</h2><p id="count">١٠ دروس</p></div><input class="search" id="search" type="search" aria-label="ابحث عن درس" placeholder="ابحث عن درس…" value="${esc(search)}"></div><div class="filters">${categories.map(c=>`<button class="filter ${filter===c?'active':''}" aria-pressed="${filter===c}" data-filter="${c}">${c}</button>`).join('')}</div><div class="cards" id="cards"></div></section>`;grid();document.querySelector('#search').addEventListener('input',e=>{search=e.target.value;grid()});main.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;main.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});grid()}));}
function lesson(l){main.innerHTML=`<a href="#home" class="back">→ جميع الدروس</a><section class="study-head"><span class="tag">${l.category}</span><h1>${l.title}</h1><p>${l.goal}</p></section><div class="study-grid"><div><section class="panel" id="explain"><span class="tag">٠١ / أفهم</span><h2>القاعدة بوضوح</h2><ul class="rules arabic">${l.rules.map(r=>`<li>${r}</li>`).join('')}</ul></section><section class="panel" id="examples"><span class="tag">٠٢ / أتأمل</span><h2>أمثلة توضّح الفكرة</h2>${l.examples.map(e=>`<div class="example"><b>${e[0]}</b><p>${e[1]}</p></div>`).join('')}</section><section class="panel note"><h2>انتبه لهذا الفرق</h2><p>${l.mistake}</p></section><section class="panel" id="practice"><span class="tag">٠٣ / أطبق</span><h2>اختبر فهمك</h2><p>أجب عن الأسئلة الأربعة، ثم اعرض نتيجتك وتفسير الإجابات.</p><div id="quiz-status" aria-live="polite"></div><form id="quiz">${l.questions.map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${q.text}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" ${quizAnswers[i]===j?'checked':''}><span>${o}</span></label>`).join('')}<div id="feedback-${i}"></div></fieldset>`).join('')}<div class="actions"><button class="primary" type="submit">اعرض نتيجتي</button><button class="secondary" id="retry" type="button" hidden>تدرب من جديد</button></div></form><p class="storage-note">إنجازك محفوظ على هذا المتصفح فقط.</p></section>${l.video?`<details class="panel"><summary>شاهد شرح الدرس</summary><p><a class="video-link" href="https://www.youtube.com/watch?v=${l.video}" target="_blank" rel="noopener">فتح فيديو الشرح المرتبط بالدرس ↗</a></p></details>`:''}<div class="actions"><a class="secondary" href="#home">جميع الدروس</a>${LESSONS.indexOf(l)<9?`<a class="primary" href="#lesson/${LESSONS[LESSONS.indexOf(l)+1].id}">الدرس التالي ←</a>`:''}</div></div><aside class="panel study-aside"><h3>مسار تعلمك</h3><p>افهم، تأمل، ثم طبق.</p><button class="secondary" data-scroll="explain">الشرح</button><button class="secondary" data-scroll="examples">الأمثلة</button><button class="primary" data-scroll="practice">ابدأ التدريب</button><button class="secondary" data-assistant>اسأل مساعد لغتي</button><button class="secondary" id="print">طباعة الملخص</button></aside></div>`;
 main.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));main.querySelector('#print').onclick=()=>window.print();main.querySelector('#quiz').addEventListener('change',e=>{if(e.target.matches('input[type=radio]'))quizAnswers[Number(e.target.name.slice(1))]=Number(e.target.value)});main.querySelector('#quiz').addEventListener('submit',grade);main.querySelector('#retry').onclick=()=>{quizAnswers={};graded=false;lesson(l);document.querySelector('#practice').scrollIntoView();bindAssistant()};bindAssistant();}
function grade(e){e.preventDefault();if(graded)return;const l=current;const status=document.querySelector('#quiz-status');if(l.questions.some((q,i)=>quizAnswers[i]===undefined)){status.innerHTML='<p class="error" role="alert">أجب عن جميع الأسئلة أولًا، ثم اعرض نتيجتك.</p>';let i=l.questions.findIndex((q,i)=>quizAnswers[i]===undefined);main.querySelector(`[name=q${i}]`).focus();return}graded=true;let score=0;l.questions.forEach((q,i)=>{let ok=q.answer===quizAnswers[i];if(ok)score++;document.querySelector('#feedback-'+i).innerHTML=`<div class="feedback ${ok?'':'wrong'}">${ok?'إجابة صحيحة':'الصواب: '+q.options[q.answer]}<br>${q.explanation}</div>`});progress[l.id]={done:true,best:Math.max(best(l.id),score),last:score};persist();status.innerHTML=`<div class="result"><strong>${score} / ٤</strong><p>${score===4?'أحسنت! أتقنت تدريب هذا الدرس.':'خطوة جميلة. راجع تفسير الإجابات ثم حاول مجددًا.'}</p></div>${storageOK?'':'<p>تعذر حفظ الإنجاز على هذا المتصفح، لكن نتيجتك ظاهرة هنا.</p>'}`;main.querySelectorAll('#quiz input').forEach(i=>i.disabled=true);main.querySelector('#quiz [type=submit]').hidden=true;main.querySelector('#retry').hidden=false;status.scrollIntoView({behavior:'smooth',block:'center'});}
function showProgress(){const count=LESSONS.filter(l=>progress[l.id]?.done).length;main.innerHTML=`<a class="back" href="#home">→ جميع الدروس</a><section class="study-head"><span class="tag">كل خطوة تصنع فرقًا</span><h1>رحلة إنجازي</h1><p>تدربت على ${count} من ١٠ دروس.</p><div class="progressbar"><span style="width:${count*10}%"></span></div><small>يعرض كل درس أفضل نتيجة تدريبية على هذا المتصفح.</small></section><div class="cards">${LESSONS.map(card).join('')}</div><p class="storage-note">هذه متابعة شخصية على جهازك، ولا تُرسل نتائجها إلى المعلم.</p><button id="reset-progress" class="secondary">مسح إنجازي من هذا الجهاز</button>`;main.querySelector('#reset-progress').onclick=()=>{if(confirm('هل تريد مسح إنجازك التدريبي من هذا المتصفح؟')){progress={};persist();showProgress()}}}
function route(){let hash=location.hash.slice(1)||'home';if(hash==='lessons'){current=null;quizAnswers={};graded=false;if(!document.querySelector('#lessons'))home();document.querySelector('#lessons').scrollIntoView();return}let id=hash.startsWith('lesson/')?hash.slice(7):null;let l=LESSONS.find(x=>x.id===id);if(l!==current){quizAnswers={};graded=false}current=l||null;if(l){graded=false;lesson(l)}else if(hash==='progress')showProgress();else if(hash==='home')home();else main.innerHTML='<section class="panel"><h1>الصفحة غير موجودة</h1><a class="primary" href="#home">العودة إلى الدروس</a></section>';document.title=l?l.title+' | لغتي':'لغتي | الصف السادس';window.scrollTo(0,0);main.focus({preventScroll:true});if(pendingPractice&&l){pendingPractice=false;document.querySelector('#practice').scrollIntoView();}}
const dialog=document.querySelector('#assistant'),select=document.querySelector('#assistant-lesson'),answer=document.querySelector('#assistant-answer');select.innerHTML=LESSONS.map(l=>`<option value="${l.id}">${l.title}</option>`).join('');
function openAssistant(){lastFocus=document.activeElement;if(current)select.value=current.id;answer.textContent='اختر ما تريد مراجعته في درس '+LESSONS.find(l=>l.id===select.value).title+'.';if(!dialog.open)dialog.showModal()}
function bindAssistant(){document.querySelectorAll('[data-assistant]').forEach(b=>b.onclick=openAssistant)}
document.querySelector('#close-assistant').onclick=()=>dialog.close();dialog.addEventListener('close',()=>lastFocus?.focus());select.onchange=()=>answer.textContent='اختر ما تريد مراجعته في درس '+LESSONS.find(l=>l.id===select.value).title+'.';
document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{const l=LESSONS.find(l=>l.id===select.value),mode=b.dataset.help;if(mode==='practice'){dialog.close();if(current?.id!==l.id){pendingPractice=true;location.hash='lesson/'+l.id}else document.querySelector('#practice').scrollIntoView();return}answer.innerHTML=`<h3>${l.title}</h3>`+(mode==='rules'?`<ul>${l.rules.map(r=>`<li>${r}</li>`).join('')}</ul>`:mode==='examples'?l.examples.map(e=>`<div class="example"><b>${e[0]}</b><p>${e[1]}</p></div>`).join(''):`<p>${l.mistake}</p>`)});
document.querySelector('#assistant-search').oninput=e=>{const query=norm(e.target.value),tokens=query.split(/\s+/).filter(t=>t.length>1&&!['ما','هي','هو','لماذا','كيف','في','علي','من','لي','اشرح'].includes(t));const matches=LESSONS.map(l=>{let title=norm(l.title),text=norm([l.title,l.goal,...l.rules,...l.examples.flat(),l.mistake].join(' '));return{l,score:tokens.reduce((n,t)=>n+(title.includes(t)?4:text.includes(t)?1:0),0)}}).filter(x=>tokens.length&&x.score>=Math.max(1,tokens.length)).sort((a,b)=>b.score-a.score).slice(0,4);const target=document.querySelector('#assistant-matches');target.innerHTML=!query?'':matches.length?matches.map(x=>`<button data-match="${x.l.id}">${x.l.title}</button>`).join(''):'<p>لم أجد شرحًا مناسبًا لهذه العبارة. اختر الدرس من القائمة.</p>';target.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>{select.value=b.dataset.match;select.onchange();document.querySelector('[data-help=rules]').click()})};
window.addEventListener('hashchange',route);bindAssistant();route();
